### PR TITLE
find log(x+1) and log(1+x)

### LINKED ISSUE #639: Unexpected data transformation when transformation in formula
When a variable is of the form `log(1 + var)` in the formula, it transforms *other* variables when we get the data... very strange

``` r
summary(iris$Sepal.Length)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>   4.300   5.100   5.800   5.843   6.400   7.900


model <- lm(Petal.Length ~ log(Sepal.Width) + Sepal.Length,
            data=iris)

# Same min-max
summary(insight::get_data(model)$Sepal.Length)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>   4.300   5.100   5.800   5.843   6.400   7.900

model <- lm(Petal.Length ~ log(1 + Sepal.Width) + Sepal.Length,
            data=iris)

# Diffrent!
summary(insight::get_data(model)$Sepal.Length)
#>    Min. 1st Qu.  Median    Mean 3rd Qu.    Max. 
#>   3.000   3.800   4.000   4.057   4.300   5.400
```

<sup>Created on 2022-09-19 by the [reprex package](https://reprex.tidyverse.org) (v2.0.1)</sup>

### PR DESCRIPTION
**Pull request by strengejacke**
Close #639

### CODE REVIEW

File: tests/testthat/test-get_data.R [hunk 1]
```diff
@@ -59,6 +59,40 @@ test_that("mgcv", {
...
+  expect_equal(s1, s2, tolereance = 1e-4)
+  expect_equal(s1, s3, tolereance = 1e-4)
+  expect_equal(s1, s4, tolereance = 1e-4)
+  expect_equal(s1, s5, tolereance = 1e-4)
+  expect_equal(s2, s3, tolereance = 1e-4)
+  expect_equal(s2, s4, tolereance = 1e-4)
+  expect_equal(s2, s5, tolereance = 1e-4)
+  expect_equal(s3, s4, tolereance = 1e-4)
+  expect_equal(s3, s5, tolereance = 1e-4)
+  expect_equal(s4, s5, tolereance = 1e-4)
```
Comment (IndrajeetPatil) [inline tests/testthat/test-get_data.R:94]: All `tolereance`s here should be replaced with `tolerance`.
